apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: airflow
    repoURL: https://airflow.apache.org
    targetRevision: "1.0.0"
  syncPolicy: {}
